# Site settings
port: 4000
highlighter: pygments
title: jEdit for JRubyArt
email: martin_p@lineone.net
description: > # this means to ignore newlines until "baseurl:"
  jEdit is an extremely configurable editor, that is very suitable for 
  JRubyArt, ruby-processing, processing.py and even vanilla processing
baseurl: "/jedit4processing" # the subpath of your site, e.g. /blog
twitter_username: monkstoneT
github_username:  monkstone

syntax-highlighting:
  enabled: true
  css: syntax.css        
# Build settings
markdown: kramdown
gems:
  - kramdown
  - jekyll-sitemap